# Generated by Django 5.2.7 on 2025-11-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('userType', models.CharField(choices=[('admin', 'Admin'), ('trainer', 'Trainer'), ('trainee', 'Trainee')], max_length=10)),
                ('subject', models.CharField(blank=True, choices=[('js', 'JavaScript'), ('css', 'CSS'), ('java', 'Java'), ('python', 'Python'), ('other', 'Other')], max_length=10, null=True)),
            ],
        ),
    ]
